FutManager/FutManager/Models/ViewModels/HomeViewModel.cs
using Shared.Models.DtoModels;
using Shared.Models.MatchModels;

namespace FutManager.Models.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<CurrentlyLiveMatch>? LiveMatches { get; set; }
        public IEnumerable<PlayerDto>? Players { get; set; }
        public IEnumerable<SquadDto>? Squads { get; set; }
    }
}

FutManager/FutManager/Controllers/HomeController.cs
using FutManager.Models.ViewModels;
using FutManager.Services;
using Microsoft.AspNetCore.Mvc;
using Shared.Models.MatchModels;

namespace FutManager.Controllers
{
    public class HomeController : Controller
    {
        private readonly IHomeService _homeService;
        private readonly IPlayerService _playerService;
        private readonly ISquadService _squadService;

        public HomeController(IHomeService homeService, IPlayerService playerService, ISquadService squadService)
        {
            _homeService = homeService;
            _playerService = playerService;
            _squadService = squadService;
        }

        public async Task<ViewResult> Index()
        {
            var model = new HomeViewModel();
            model.LiveMatches = await _homeService.GetAllActiveMatches();
            model.Players = await _playerService.GetPlayersForPage(0);
            model.Squads = await _squadService.GetSquadsForPage(0);

            ViewData["Title"] = "Home";
            return View(model);
        }
    }
}

FutManager/FutManager/Controllers/LiveMatchController.cs
using Microsoft.AspNetCore.Mvc;

namespace FutManager.Controllers
{
    public class LiveMatchController : Controller
    {
        public IActionResult Index(string channel)
        {
            ViewData["Title"] = "Live";
            ViewBag.Channel = channel;
            return View();
        }
    }
}

FutManager/FutManager/Controllers/PlayerController.cs
using FutManager.Services;
using Microsoft.AspNetCore.Mvc;
using Shared.Models.DtoModels;

namespace FutManager.Controllers
{
    [ApiController]
    [Route("PlayerManager")]
    public class PlayerController : Controller
    {
        private readonly IPlayerService _playerService;

        public PlayerController(IPlayerService playerService)
        {
            _playerService = playerService;
        }
        
        [Route("AddPlayer")]        
        [HttpPost]
        public async Task<IActionResult> AddPlayer([FromBody]PlayerDto playerDto)
        {
            int response = await _playerService.AddPlayer(playerDto);
            return StatusCode(response);
        }
        
        [Route("GetPlayers/{page}")]
        [HttpGet]
        public async Task<IActionResult> GetPlayers(int page)
        {
            var players = await _playerService.GetPlayersForPage(page);
            return Ok(players);
        }
        
        [Route("DeletePlayer/{id}")]
        [HttpDelete]
        public async Task<IActionResult> DeletePlayer(int id)
        {
            int response = await _playerService.DeletePlayer(id);
            return StatusCode(response);
        }

        [Route("GetPlayer/{id}")]
        [HttpGet]
        public async Task<IActionResult> GetPlayer(int id)
        {
            var player = await _playerService.GetPlayer(id);
            return Ok(player);
        }

        [Route("UpdatePlayer")]
        [HttpPut]
        public async Task<IActionResult> UpdatePlayer([FromBody] PlayerDto playerDto)
        {
            int response = await _playerService.UpdatePlayer(playerDto);
            return StatusCode(response);
        }

        [Route("AddPlayerToSquad/{squadId}/{playerId}")]
        [HttpPost]
        public async Task<IActionResult> AddPlayerToSquad(int squadId, int playerId)
        {
            int response = await _playerService.AddPlayerToSquad(squadId, playerId);
            return StatusCode(response);
        }
    }
}

FutManager/FutManager/Controllers/SquadController.cs
using FutManager.Services;
using Microsoft.AspNetCore.Mvc;
using Shared.Models.DtoModels;

namespace FutManager.Controllers
{
    [ApiController]
    [Route("SquadManager")]
    public class SquadController : Controller
    {
        private readonly ISquadService _squadService;
        public SquadController(ISquadService squadService)
        {
            _squadService = squadService;
        }
    
        [Route("AddSquad/{name}/{balance}")]
        [HttpPost]
        public async Task<IActionResult> AddSquad(string name, int balance)
        {
            int response = await _squadService.AddSquad(name, balance);
            return StatusCode(response);
        }
         
        [Route("GetSquads/{page}")]
        [HttpGet]
        public async Task<IActionResult> GetSquads(int page)
        {
            var squads = await _squadService.GetSquadsForPage(page);
            return Ok(squads);
        }
        
        [Route("DeleteSquad/{id}")]
        [HttpDelete]
        public async Task<IActionResult> DeleteSquad(int id)
        {
            int response = await _squadService.DeleteSquad(id);
            return StatusCode(response);
        }

        [Route("UpdateSquad")]
        [HttpPut]
        public async Task<IActionResult> UpdateSquad([FromBody]SquadDto squadDto)
        {
            int response = await _squadService.UpdateSquad(squadDto);
            return StatusCode(response);
        }
    }
}

FutManager/FutManager/Views/Home/Index.cshtml
@model FutManager.Models.ViewModels.HomeViewModel
@{
    Layout = "../Shared/_Layout.cshtml";
    var arr = Shared.Enums.FieldPositions.GetNames(typeof(Shared.Enums.FieldPositions));
}

<div class="main">
    <div class="columnFlex borderLine">
        <h1 class="sqParagraph">Squad Manager</h1>
        <p class="drop">Add Squad</p>
        <div class="addSquad displayNone">
            <input id="squadName" placeholder="Name"/>
            <input id="squadBalance" placeholder="Balance" type="number" min="0"/>
            <button id="squadAdd">Add</button>
        </div>
        <p class="drop">Manage Squad</p>
        <div class="manageSquad displayNone">
            <button id="previousSquads">&lt</button>
            <div id="shlSquads" class="showList">
                @{
                    if (Model.Squads != null)
                    {
                        foreach (var squad in Model.Squads)
                        {
                            <div class="borderLine">
                                <p>Name: @squad.Name</p>
                                <p>Balance: @squad.Balance</p>
                                <input id="deleteID" type="hidden" value="@squad.Id"/>
                                <button id="changeSquad">Change</button>
                                <button id="deleteSquad">Delete</button>
                            </div>
                        }
                    }
                }
            </div>
            <button id="nextSquads">&gt</button>
        </div>
        <p class="drop">Add Player</p>
        <div class="addPlayer displayNone">
            <input id="playerName" placeholder="First name" />
            <input id="playerLName" placeholder="Last name" />
            <input id="playerRating" placeholder="Rating" type="number" min="0" />
            <input id="playerAge" placeholder="Age" type="number" min="16" />
            <input id="playerNationality" placeholder="Nationality" />
            <input id="playerSquad" placeholder="Squad" />
            <select id="playerPosition">
                @{ 
                    for (int i = 0; i < arr.Length; i++)
                    {
                        <option value="@i">@arr[i]</option>
                    }
                }
            </select>
            <button id="playerAdd">Add</button>
        </div>
        <p class="drop">Manage Player</p>
        <div class="managePlayer displayNone">
            <button id="previousPlayers">&lt</button>
            <div id="shlPlayers" class="showList">
                @{
                    if (Model.Players != null)
                    {
                        foreach (var player in Model.Players)
                        {
                            <div class="borderLine">
                                <p>Name: @player.FirstName</p>
                                <p>Rating: @player.OverallRating</p>
                                <p>Nationality: @player.Nationality</p>
                                <input id="deleteID" type="hidden" value="@player.Id"/>
                                <button id="changePlayer">Change</button>
                                <button id="deletePlayer">Delete</button>
                            </div>
                        }
                    }
                }
            </div>
            <button id="nextPlayers">&gt</button>
        </div>
    </div>
    <div class="matchmaking columnFlex borderLine">
        <h1>Matchmaking</h1>
        <p class="drop">Start Practice Simulation</p>
        <div class="startFriendlyMatch displayNone ">
            <button onclick="startPractice()">Start Practice</button>
        </div>    
        
        <div>
            <p class="drop">Schedule Friendly</p>
            <div class="startFriendlyMatch displayNone">
                <input type="datetime-local" id="meeting-time"
                       name="match-time"
                       min="2023-01-01T00:00" max="2024-01-01T00:00">
                <button onclick="scheduleFriendly()">Schedule Friendly</button>
            </div>    
        </div>
    </div>
    <div class="matches borderLine">
        <h1>Currently Live Matches</h1>
        @{
            if (Model.LiveMatches != null)
            {
                foreach (var liveMatch in Model.LiveMatches)
                {
                    <a href="@Url.Action("Index", "LiveMatch", new { channel = liveMatch.Channel })">@liveMatch.Channel</a>
                }
            }
        }
    </div>
    
    <div class="overlay">
        <div id="popupPlayer" class="popup">
            <input type="hidden"/>
            <label>First Name:</label>
            <input id="changePlayerName" />
            <label>Last Name:</label>
            <input id="changePlayerLName" />
            <label>Rating:</label>
            <input id="changePlayerRating" type="number" />
            <label>Age:</label>
            <input id="changePlayerAge" type="number"/>
            <label>Nationality:</label>
            <input id="changePlayerNationality" />
            <label>Squad:</label>
            <input id="changePlayerSquad" />
            <label>Position:</label>
            <select id="changePlayerPosition">
                @{
                    for (int i = 0; i < arr.Length; i++)
                    {
                        <option value="@i">@arr[i]</option>
                    }
                }
            </select>
            <button id="updatePlayer">Confirm</button>
            <button id="cancelBtnPlayers">Cancel</button>
        </div>
        <div id="popupSquad" class="popup">
            <input type="hidden" />
            <label>Name:</label>
            <input id="changeSquadName" />
            <label>Balance:</label>
            <input id="changeSquadBalance" type="number" />
            <p class="drop">Add Player To Squad</p>
            <div class="managePlayer displayNone">
                <button id="previousPlayers">&lt</button>
                <div id="shlPlayers" class="showList">
                    @{
                        if (Model.Players != null)
                        {
                            foreach (var player in Model.Players)
                            {
                                <div class="borderLine">
                                    <p>Name: @player.FirstName</p>
                                    <p>Rating: @player.OverallRating</p>
                                    <p>Nationality: @player.Nationality</p>
                                    <input id="addID" type="hidden" value="@player.Id" />
                                    <button id="addPlayer">Add</button>
                                </div>
                            }
                        }
                    }
                </div>
                <button id="nextPlayers">&gt</button>
            </div>

            <button id="updateSquad">Confirm</button>
            <button id="cancelBtnSquads">Cancel</button>
        </div>
    </div>

</div>
<script src="scripts/home.js"></script>

FutManager/FutManager/Views/LiveMatch/Index.cshtml
@model dynamic
<h1>Live Scores Open console for live messages</h1>

<div id="scores"></div>
<script src="https://cdn.jsdelivr.net/npm/@@aspnet/signalr@1.1.4/dist/browser/signalr.js"></script>
<script>
        var channel = '@ViewBag.Channel';
        var connection = new signalR.HubConnectionBuilder().withUrl("/redisHub").build();
        
        connection.on("ReceiveMessage", function (score) {
            console.log(score);
        });
        
        connection.start().then(function () {
            connection.invoke("StreamMatches", channel).catch(function (err) {
                return console.error(err.toString());
            });
        });
</script>

FutManager/FutManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en-US">
    <head>
        <title>@ViewData["Title"]</title>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="styles/home.css"/>
        <link rel="stylesheet" href="styles/popupPlayer.css"/>
    </head>
<body>
@Html.AntiForgeryToken()
@RenderBody()
</body>
</html>